language: ruby

rvm:
  - ruby-head
  - jruby-head
  - rbx-head
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
  - 1.9.2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head

branches:
  only:
    - master

before_install:
  - gem install bundler